/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20LunaSol from "./ERC20Luna.sol";
export type { erc20LunaSol };
import type * as interfaces from "./Interfaces";
export type { interfaces };
